# Generated by Django 4.1.2 on 2022-10-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('name', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('on_sale', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=5)),
                ('color', models.CharField(max_length=50)),
                ('tags', models.JSONField()),
            ],
        ),
    ]
